### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by SHOWCRASH** [qyful/AWCMaster#1]
Hello, I'm having trouble uploading an audio file to the program. Can you tell me how to fix it? Screenshot attached

![Cannot open file](https://github.com/user-attachments/assets/eee65570-97e0-4bde-9a9a-915611dff77c)

**Comment by qyful** [comment]
Hi @SHOWCRASH, does this happen with any other MP3 files? Also, would you please upload the MP3 file for me to look at. Thanks!

**Comment by SHOWCRASH** [comment]
This happens with a lot of .mp3 and .wav files that I'm trying to add to the program. Here is one of them  
https://drive.google.com/file/d/1JkTtXAaZTcTCGDHckJq-SQ4JTXdmqaWi/view?usp=sharing

**Comment by qyful** [comment]
Seems to be working fine for me:
![image](https://github.com/user-attachments/assets/c99571bb-3e97-4475-8dab-6186f2a926a7)

I guess that it's not picking up the `ffmpeg` distribution that is packaged in the executable. Please try:
1. Downgrading to a previous release;
2. Downloading `ffmpeg` and adding it to your system PATH; or
3. Cloning this repository and adding the `ffmpeg.exe` and `ffprobe.exe` executables in the root directory.

I'll look and see if I can fix this issue over the next few days. Thanks for reporting it!

**Comment by SHOWCRASH** [comment]
Good. I'll try

**Comment by SHOWCRASH** [comment]
> Seems to be working fine for me: ![image](https://private-user-images.githubusercontent.com/46076616/363435763-c99571bb-3e97-4475-8dab-6186f2a926a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwODYsIm5iZiI6MTcyNTI2Mzc4NiwicGF0aCI6Ii80NjA3NjYxNi8zNjM0MzU3NjMtYzk5NTcxYmItM2U5Ny00NDc1LThkYWItNjE4NmYyYTkyNmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDM2NDBmZWFkMGYwMzRiNTQyYzIwNzJjN2RkMWVjMGZjZWYxZjU0YjY5NzYyY2ZkZTE0ZjQ5ZDI1YWM4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zvh3lO56gE94zZ8HioM6Us3_vNVY8w2PdLc1d9LTSys)
> 
> I guess that it's not picking up the `ffmpeg` distribution that is packaged in the executable. Please try:
> 
> 1. Downgrading to a previous release;
> 2. Downloading `ffmpeg` and adding it to your system PATH; or
> 3. Cloning this repository and adding the `ffmpeg.exe` and `ffprobe.exe` executables in the root directory.
> 
> I'll look and see if I can fix this issue over the next few days. Thanks for reporting it!

I understood what needs to be done and I will tell you what I did. I downloaded ffmpeg 6.1 and registered the system path for it via the CMD command line. It didn't help

![Screenshot_2](https://github.com/user-attachments/assets/e2ea7181-bfc6-476d-b0e2-06c4d6654e06)

I have placed 2 files ffmpeg.exe and ffprobe.exe to the root folder of the project. I took these 2 files from the bin folder. It also didn't help

![Screenshot_1](https://github.com/user-attachments/assets/eac659b0-4405-4223-b20c-1b12ba3caace)

I use pycharm 

Maybe I should use another development environment?

**Comment by qyful** [comment]
Hi! I'm sorry to hear you're still having issues with the release. Try moving the `ffmpeg.exe` and `ffprobe.exe` files into the `/src` folder as that is technically the project's root directory. After that it _should_ work!

Let me know if this issue persists 😄

**Comment by SHOWCRASH** [comment]
You are the best! Everything worked. Thank you very much!
![Screenshot_1](https://github.com/user-attachments/assets/345226cc-7068-4a95-add2-3e960601cc97)
